import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 24,
    paddingVertical: 40,
  },
  centerContent: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  image: {
    width: 160,
    height: 160,
    resizeMode: 'contain',
    marginBottom: 12,
  },
  title: {
    fontSize: 22,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#222',
    textAlign: 'center',
  },
  buttonContainer: {
    width: '100%',
    marginBottom: 24,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  button: {
    backgroundColor: '#2476FF',
    borderRadius: 28,
    paddingVertical: 16,
    paddingHorizontal: 32,
    width: '100%',
    alignItems: 'center',
    marginBottom: 16,
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '500',
  },
  link: {
    color: '#1E6BE8',
    fontSize: 16,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  modalContent: {
    backgroundColor: '#F7F8F8',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 30,
    alignItems: 'center',
    minHeight: 632,
    display: 'flex',
    flexDirection: 'column',
  },
  qr: {width: 80, height: 80, marginBottom: 12},
  qrText: {
    textAlign: 'center',
    marginBottom: 16,
    color: '#070707',
    width: 192,
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 16,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    width: '100%',
    marginVertical: 12,
    borderStyle: 'solid',
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 8,
  },
  label: {fontWeight: '500', color: '#070707', fontSize: 14, lineHeight: 20},
  value: {
    color: '#070707',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  cancelText: {
    color: '#2476FF',
    fontSize: 16,
    textAlign: 'center',
    marginTop: 12,
  },
  modalCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    display: 'flex',
    flexDirection: 'column',
    padding: 16,
    width: '100%',
    alignItems: 'center',
    paddingVertical: 40,
  },
  modalBtn: {
    backgroundColor: '#2476FF',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 24,
    width: '100%',
    alignItems: 'center',
  },
  modalBtns: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    width: '100%',
    gap: 16,
    marginTop: 16,
  },
  infoContainer: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    gap: 8,
  },
});

export default styles;
