import { StyleSheet } from 'react-native';

export const _styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  profileHeader: {
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 58,
  },
  avatarContainer: {
    position: 'relative',
    marginBottom: 18,
  },
  avatar: {
    width: 86,
    height: 86,
    borderRadius: 40,
    backgroundColor: '#F2F2F2',
  },
  addIcon: {
    position: 'absolute',
    right: -2,
    bottom: 0,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#fff',
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addIconImg: {
    width: 18,
    height: 18,
  },
  userName: {
    color: '#070707',
    textAlign: 'center',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 26,
    marginTop: 4,
    marginBottom: 0,
    fontFamily: 'SF Pro',
  },
  section: {
    width: '100%',
    backgroundColor: 'transparent',
    borderRadius: 12,
    marginBottom: 48,
    borderColor: 'red',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F7F8F8',
    fontFamily: 'SF Pro',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 8,
    marginBottom: 6,
  },
  menuIconText: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuIcon: {
    width: 24,
    height: 24,
    marginRight: 12,
  },
  menuText: {
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 20,
    color: '#070707',
    fontFamily: 'SF Pro',
  },
  arrowIcon: {
    width: 24,
    height: 24,
  },
  personalInfoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 24,
  },
  personalInfoHeaderTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: 'bold',
    marginRight: 24,
    fontFamily: 'SF Pro',
  },
  divider: {
    height: 1,
    backgroundColor: '#E5E5E5',
    marginBottom: 6,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 12,
  },
  infoIcon: {
    width: 24,
    height: 24,
    marginRight: 6,
    objectFit: 'contain',
  },
  infoText: {
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: 20,
    letterSpacing: -0.28,
    color: '#070707',
    flex: 1,
    fontFamily: 'SF Pro',
  },
  goBackIcon: {
    width: 24,
    height: 24,
  },
  editButton: {
    color: '#2176FF',
    fontSize: 15,
    fontFamily: 'SF Pro',
  },
  logoutModalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    flex: 1,
  },
  logoutModalContainer: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 34,
    alignItems: 'center',
    backgroundColor: 'transparent',
    zIndex: 999,
  },
  logoutModalButton: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    paddingVertical: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  logoutModalButtonText: {
    color: '#FF3B30',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'SF Pro',
    textAlign: 'center',
  },
  logoutModalCancelText: {
    color: '#2176FF',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'SF Pro',
    textAlign: 'center',
  },
});
export default _styles;